/**
 * Bundles `function.ts` into a self-contained Vercel Node function directory
 * (`functions/agent-surface.func`) inside the Build Output folder.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
// Static import: Astro runs integration hooks through Vite's module runner, which is
// closed by the time `astro:build:done` fires, so a dynamic import would have no loader.
import * as esbuild from 'esbuild';

/** Function name the injected routes target (`dest`), and its Build Output directory stem. */
export const AGENT_FUNCTION = 'agent-surface';

export interface BundleAgentFunctionOptions {
  /** Absolute path of the TypeScript entry (`src/lib/agent-surface/function.ts`). */
  entry: string;
  /** Build Output `functions` directory. */
  functionsDir: string;
  /** Vercel Node runtime id; defaults to the one the Astro render function uses. */
  runtime?: string;
}

export interface BundledAgentFunction {
  dir: string;
  handler: string;
  runtime: string;
  bytes: number;
}

export const DEFAULT_RUNTIME = 'nodejs22.x';

/** Reads the runtime the Astro adapter chose so both functions run on the same Node version. */
export async function astroRenderRuntime(functionsDir: string): Promise<string | null> {
  try {
    const config = JSON.parse(await readFile(join(functionsDir, '_render.func', '.vc-config.json'), 'utf8')) as { runtime?: string };
    return typeof config.runtime === 'string' ? config.runtime : null;
  } catch {
    return null;
  }
}

export async function bundleAgentFunction(options: BundleAgentFunctionOptions): Promise<BundledAgentFunction> {
  const dir = join(options.functionsDir, `${AGENT_FUNCTION}.func`);
  const handler = 'index.mjs';
  await mkdir(dir, { recursive: true });
  const result = await esbuild.build({
    entryPoints: [options.entry],
    outfile: join(dir, handler),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    minify: false,
    sourcemap: false,
    logLevel: 'silent',
    metafile: true,
    banner: { js: '// Generated by reinstate-agent-surface; do not edit.' },
  });
  const runtime = options.runtime ?? (await astroRenderRuntime(options.functionsDir)) ?? DEFAULT_RUNTIME;
  await writeFile(
    join(dir, '.vc-config.json'),
    `${JSON.stringify({ runtime, handler, launcherType: 'Nodejs', shouldAddHelpers: false }, null, '\t')}\n`,
    'utf8',
  );
  await writeFile(join(dir, 'package.json'), '{"type":"module"}\n', 'utf8');
  const bytes = Object.values(result.metafile?.outputs ?? {}).reduce((sum, output) => sum + output.bytes, 0);
  return { dir, handler, runtime, bytes };
}
